### PR TITLE
Remember scroll position

### LINKED ISSUE #58: Back button doesn't work as expected after following a nav link or anchor
If you view one section then click a link on nav or an anchor, then click back, you are not taken to the previous section, but to the previous site you were browsing.

### PR DESCRIPTION
**Pull request by 36degrees**
This fixes #58.

Because we are using a scrollable div rather than scrolling the document body itself, browser behaviour is not quite what you’d expect. For example:

1) When navigating to an external link, using the browser back button takes you back to the top of the documentation, rather than remembering where you were.
2) When navigating the document using the table of contents, clicking the back button has no effect at all.

This fixes both of those problems by continuously storing the scroll offset using the browser’s history API as the user scrolls. Then, on initial page load (refreshing, or navigating back to the document from an external link) and whenever a `popstate` event is fired (the user clicks back after clicking an internal link), the scroll offset from any previous history state is restored.

We use `requestAnimationFrame` to debounce scroll events, polyfilling this for older browsers.

In order to maintain consistency between the URL that’s displayed in the browser and the part of the page the user is returned to, we also keep the two in sync by re-writing the URL as part of that same `replaceState` call. The fact that we need to know this is part of the reason why this code is not a separate module as you might expect.

Best viewed as individual commits as I've also renamed the file.

https://trello.com/c/wKnkz0EF/542-back-button-doesn-t-work-as-expected-mvp

### CODE REVIEW

File: template/source/javascripts/modules/in-page-navigation.js [hunk 1]
```diff
@@ -0,0 +1,93 @@
...
+
+  Modules.InPageNavigation = function InPageNavigation() {
+    var $tocPane;
+    var $contentPane;
+    var $tocItems;
+
+    var animationFrameRequested = false;
+
+    this.start = function start($element) {
+      if (!Modernizr.history) {
```
Comment (mcmillan) [inline template/source/javascripts/modules/in-page-navigation.js]: If we include this guard clause here, I'm pretty sure we'll stop the navigation being highlighted on scroll – is that intended?

I guess you could argue that most browsers that don't have the history API also don't have flexbox, so it won't be too useful, but might be nice to decouple that regardless.

File: template/source/javascripts/modules/in-page-navigation.js [hunk 2]
```diff
@@ -0,0 +1,93 @@
...
+    };
+
+    function restoreScrollPosition(state) {
+      if (state && state.scrollTop) {
+        $contentPane.scrollTop(history.state.scrollTop);
+      }
+    }
+
+    function handleScrollEvent() {
+      var activeTocItem = tocItemForFirstElementInView();
```
Comment (mcmillan) [inline template/source/javascripts/modules/in-page-navigation.js]: Slightly pedantic, but as this returns a jQuery object, can we call this `$activeTocItem` for consistency? Appears to be what we're doing elsewhere.

File: template/source/javascripts/modules/in-page-navigation.js [hunk 3]
```diff
@@ -0,0 +1,93 @@
...
+
+        if ($heading.position().top <= 0) {
+          target = $this;
+        }
+      });
+
+      return target;
+    }
+
+    function withAnimationFrame(callback) {
```
Comment (mcmillan) [inline template/source/javascripts/modules/in-page-navigation.js]: I wonder if it's a better idea to use an off-the-shelf debounce function rather than rolling our own – in the past I've included [lodash.debounce](https://www.npmjs.com/package/lodash.debounce). That's a node module, but you can generate a lodash build with just the debounce function via `lodash -d include=debounce exports=global` (after `npm install -g lodash-cli`).

Ironically that doesn't actually use `requestAnimationFrame`, so this implementation is perhaps a touch more performant – I'll leave it up to you.

File: template/source/javascripts/start-modules.js [hunk 4]
```diff
@@ -1,7 +1,7 @@
 //= require govuk/modules
 //= require modules/anchored-headings
+//= require modules/in-page-navigation
```
Comment (mcmillan) [inline template/source/javascripts/start-modules.js]: :+1: This is a better name.
